version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: ff_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ff_backend
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/feature-flags
      - JWT_SECRET=change_this_in_production
      - JWT_EXPIRES_IN=7d
      - SUPER_ADMIN_EMAIL=superadmin@byepo.com
      - SUPER_ADMIN_PASSWORD=SuperAdmin@123
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
